<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.7 ./models/macintosh.glb --transform --types -o ./src/lib/Mac.svelte
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group | undefined }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube003: THREE.Mesh
      Cube003_1: THREE.Mesh
      keyboard: THREE.Mesh
      keys: THREE.Mesh
    }
    materials: {
      surface_1: THREE.MeshStandardMaterial
      screen: THREE.MeshPhysicalMaterial
      surface: THREE.MeshStandardMaterial
      key: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/macintosh-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, 0.6, 0.1]}
      rotation={[-0.08, 0, 0]}
      scale={[0.48, 0.54, 0.37]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube003.geometry}
        material={gltf.materials.surface}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_1.geometry}
        material={gltf.materials.screen}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.keyboard.geometry}
      material={gltf.materials.surface}
      position={[0, 0.05, 0.72]}
      scale={[0.53, 0.04, 0.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.keys.geometry}
      material={gltf.materials.key}
      position={[0.4, 0.1, 0.8]}
      scale={[0.08, 0.04, 0.04]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
