<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.7 ./models/room.glb --output ./src/lib/Room.svelte --t --shadows --transform --keepnames --keepgroups -j
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    joystickLeftRef = $bindable(),
    joystickRightRef = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    joystickLeftRef?: THREE.Group
    joystickRightRef?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group | undefined }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Plane: THREE.Mesh
      Plane_1: THREE.Mesh
      Tube_top: THREE.Mesh
      Tubes_Vertical: THREE.Mesh
      Tube_Bottom: THREE.Mesh
      Icosphere: THREE.Mesh
      Icosphere_1: THREE.Mesh
      Arcade: THREE.Mesh
      Plane006: THREE.Mesh
      Table: THREE.Mesh
      Plane011: THREE.Mesh
      Plane001_1: THREE.Mesh
      Plane001_2: THREE.Mesh
      Joystick_Left_Base: THREE.Mesh
      Joystick_Right_Base: THREE.Mesh
      Plane004_1: THREE.Mesh
      Plane004_2: THREE.Mesh
      Plane004_3: THREE.Mesh
      Tabletop: THREE.Mesh
      Plane010: THREE.Mesh
      Plane008: THREE.Mesh
      Plane008_1: THREE.Mesh
      Plane013: THREE.Mesh
      Plane015: THREE.Mesh
    }
    materials: {
      PaletteMaterial001: THREE.MeshStandardMaterial
      PaletteMaterial002: THREE.MeshStandardMaterial
      PaletteMaterial003: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/room-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="Walls"
        scale={4}
      >
        <T.Mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Plane_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane_1.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
      </T.Group>
      <T.Mesh
        name="Tube_top"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Tube_top.geometry}
        material={gltf.materials.PaletteMaterial002}
        position={[0.87, 0, 0]}
        scale={4}
      />
      <T.Mesh
        name="Tubes_Vertical"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Tubes_Vertical.geometry}
        material={gltf.materials.PaletteMaterial002}
        position={[0.26, 0, 0]}
        scale={4}
      />
      <T.Mesh
        name="Tube_Bottom"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Tube_Bottom.geometry}
        material={gltf.materials.PaletteMaterial002}
        position={[0.87, -0.36, 0]}
        scale={4}
      />
      <T.Group
        name="Joystick_Left"
        bind:ref={joystickLeftRef}
        position={[-2.4, 2.27, 2.74]}
        rotation={[0, 0, -0.26]}
        scale={0.06}
      >
        <T.Mesh
          name="Icosphere"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Icosphere.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Icosphere_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Icosphere_1.geometry}
          material={gltf.materials.PaletteMaterial002}
        />
      </T.Group>
      <T.Group
        name="Joystick_Right"
        bind:ref={joystickRightRef}
        position={[-2.42, 2.28, 1.96]}
        rotation={[0, 0, -0.26]}
        scale={0.06}
      >
        <T.Mesh
          name="Icosphere"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Icosphere.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Icosphere_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Icosphere_1.geometry}
          material={gltf.materials.PaletteMaterial002}
        />
      </T.Group>
      <T.Mesh
        name="Arcade"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Arcade.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[-2.61, 2.27, 1.64]}
        rotation={[0, 0, -0.26]}
        scale={0.04}
      />
      <T.Mesh
        name="Plane006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane006.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[-2.61, 2.27, 2.39]}
        rotation={[0, 0, -0.26]}
        scale={0.04}
      />
      <T.Mesh
        name="Table"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Table.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[2.19, -0.51, -1.3]}
        scale={0.11}
      />
      <T.Mesh
        name="Plane011"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane011.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[2, 1.67, -2.77]}
        rotation={[0, -0.38, 0]}
        scale={[0.87, 0.5, 0.5]}
      />
      <T.Group
        name="Plane014"
        position={[-2.07, 1.7, -2.65]}
        rotation={[0, 0.32, 0]}
        scale={[0.71, 0.4, 0.4]}
      >
        <T.Mesh
          name="Plane001_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane001_1.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Plane001_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane001_2.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
      </T.Group>
      <T.Mesh
        name="Joystick_Left_Base"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Joystick_Left_Base.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[-2.4, 2.27, 2.74]}
        rotation={[0, 0, -0.26]}
        scale={0.06}
      />
      <T.Mesh
        name="Joystick_Right_Base"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Joystick_Right_Base.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[-2.42, 2.28, 1.96]}
        rotation={[0, 0, -0.26]}
        scale={0.06}
      />
      <T.Group
        name="Plane005"
        position={[-2.98, 0, 1.72]}
        scale={[0.91, 0.91, 1.36]}
      >
        <T.Mesh
          name="Plane004_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_1.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Plane004_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_2.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Plane004_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_3.geometry}
          material={gltf.materials.PaletteMaterial003}
        />
      </T.Group>
      <T.Mesh
        name="Tabletop"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Tabletop.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[-0.31, -0.51, -2.43]}
        scale={[2.78, 1.42, 1.42]}
      />
      <T.Mesh
        name="Plane010"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane010.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[1.15, 1.86, -2.25]}
        rotation={[0, -0.38, 0]}
        scale={[1.23, 0.71, 0.71]}
      />
      <T.Group
        name="Plane012"
        position={[1.15, 1.86, -2.25]}
        rotation={[0, -0.38, 0]}
        scale={[1.23, 0.71, 0.71]}
      >
        <T.Mesh
          name="Plane008"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane008.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
        <T.Mesh
          name="Plane008_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane008_1.geometry}
          material={gltf.materials.PaletteMaterial001}
        />
      </T.Group>
      <T.Mesh
        name="Plane013"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane013.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[2, 1.67, -2.77]}
        rotation={[0, -0.38, 0]}
        scale={[0.87, 0.5, 0.5]}
      />
      <T.Mesh
        name="Plane015"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane015.geometry}
        material={gltf.materials.PaletteMaterial001}
        position={[-2.07, 1.7, -2.65]}
        rotation={[0, 0.32, 0]}
        scale={[0.71, 0.4, 0.4]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
