<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.7 ./models/room.glb --o ./src/lib/Room.svelte --t --shadows --transform --keepnames
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group | undefined }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Walls: THREE.Mesh
      Tube_top: THREE.Mesh
      Plane005: THREE.Mesh
    }
    materials: {
      PaletteMaterial001: THREE.MeshStandardMaterial
      PaletteMaterial002: THREE.MeshStandardMaterial
      PaletteMaterial003: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/room-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Walls"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Walls.geometry}
      material={gltf.materials.PaletteMaterial001}
      scale={4}
    />
    <T.Mesh
      name="Tube_top"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Tube_top.geometry}
      material={gltf.materials.PaletteMaterial002}
      position={[0.87, 0, 0]}
      scale={4}
    />
    <T.Mesh
      name="Plane005"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane005.geometry}
      material={gltf.materials.PaletteMaterial003}
      position={[-2.98, 0, 1.72]}
      scale={[0.91, 0.91, 1.36]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
